Avoid errors under x86/64:
FAILED: [code=1] CMakeFiles/ubox.dir/avl-cmp.c.o
/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc -Dubox_EXPORTS -I/workspaces/openwrt_main/staging_dir/target-x86_64_musl/usr/include/json-c -pipe -Os -fno-caller-saves -fno-plt -fhonour-copts -ffile-prefix-map=/workspaces/openwrt_main/build_dir/target-x86_64_musl/libubox-2026.02.13~1aa36ee7=libubox-2026.02.13~1aa36ee7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wl,-z,pack-relative-relocs -I/workspaces/openwrt_main/staging_dir/target-x86_64_musl/usr/include  -I/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/usr/include -I/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/include -I/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/include/fortify -DNDEBUG -fPIC   -Wall -Werror -Wextra -Werror=implicit-function-declaration -Wformat -Werror=format-security -Werror=format-nonliteral -Os -std=gnu99 -g3 -Wmissing-declarations -Wno-unused-parameter -MD -MT CMakeFiles/ubox.dir/avl-cmp.c.o -MF CMakeFiles/ubox.dir/avl-cmp.c.o.d -o CMakeFiles/ubox.dir/avl-cmp.c.o -c '/workspaces/openwrt_main/build_dir/target-x86_64_musl/libubox-2026.02.13~1aa36ee7/avl-cmp.c'
In file included from /workspaces/openwrt_main/build_dir/target-x86_64_musl/libubox-2026.02.13~1aa36ee7/blob.h:26,
                 from /workspaces/openwrt_main/build_dir/target-x86_64_musl/libubox-2026.02.13~1aa36ee7/avl-cmp.c:18:
/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/include/fortify/stdio.h: In function 'snprintf':
/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/include/fortify/stdio.h:101:9: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
  101 |         return __orig_snprintf(__s, __n, __f, __builtin_va_arg_pack());
      |         ^~~~~~
/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/include/fortify/stdio.h: In function 'sprintf':
/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/include/fortify/stdio.h:110:17: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
  110 |                 __r = __orig_snprintf(__s, __b, __f, __builtin_va_arg_pack());
      |                 ^~~
/workspaces/openwrt_main/staging_dir/toolchain-x86_64_gcc-14.3.0_musl/include/fortify/stdio.h:114:17: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
  114 |                 __r = __orig_sprintf(__s, __f, __builtin_va_arg_pack());
      |                 ^~~